version: '2'
services:
  pianist-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/pianist/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pianist
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
